### ISSUE TITLE
现在这个框架实际用在项目里没有呀

### ISSUE THREAD

**Issue by yutouxiansheng** [xchengDroid/retrofit-helper#2]

**Comment by xchengDroid** [comment]
公司的项目在用！ 请问你有什么问题吗

**Comment by yutouxiansheng** [comment]
> 公司的项目在用！ 请问你有什么问题吗

玩Android上看到你这个封装框架，看到你最近一直在改动，以为还没有实际应用呢。学习下你得代码。

**Comment by xchengDroid** [comment]
@yutouxiansheng  一直会更新，现在添加了Lifecycle 管理生命周期！一直在更新做一些小的优化！
